### ISSUE TITLE
Installation trouble (VirtualBox)

### ISSUE THREAD

**Issue by oddrunpauline** [NatLibFi/Annif-tutorial#10]
I've just installed VirtualBox on my Windows 10 laptop, downloaded Annif-tutorial and added the Annif-tutorial image to VirtualBox, - all  according to tutorial instruction video. 
When trying to start the image (green arrow), I get the following error message:

*****************************************************************
Failed to open a session for the virtual machine annif-tutorial.
Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).
VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED).
Result   Code: | E_FAIL (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

Any idea what to do?

**Comment by juhoinkinen** [comment]
Hi,

The message says that VT-x option is not enabled in BIOS of your computer, can you check that? [This page](https://2nwiki.2n.cz/pages/viewpage.action?pageId=75202968) has instructions for enabling VT-x (it is written for Access Commander case but never mind that). 

Note also the last lines "if you have enabled these settings within the BIOS..." (more details on disabling Hyper-V can be found from [this answer](https://community.cloudera.com/t5/Support-Questions/VT-x-is-not-available-VERR-VMX-NO-VMX-Error-for-HDP-3-0-1-on/m-p/243936/highlight/true#M205731)).

-Juho

**Comment by oddrunpauline** [comment]
Hi,
Thanks! Although I do not have administration privileges on my laptop, I was still able to access  to BIOS settings to enable VTx, - to my great surprise. And it worked! So far, so good.
